var LDItemInfoUserMutable = require('./LDItemInfoUserMutable');
var LDAppStore = require('./LDAppStore');
var LDAppScreenshot = require('./LDAppScreenshot');

function LDAppInfoUserMutable(e){
	LDItemInfoUserMutable.call(this,e);
	if(!e)return;
	var $=this;
	$.AndroidEnabled=e['ae'];
	$.AndroidDrawer=e['adr'];
	$.AndroidEditor=e['aed'];
	$.AndroidGame=e['aga'];
	$.IOSEnabled=e['ie'];
	$.IOSDrawer=e['idr'];
	$.IOSEditor=e['ied'];
	$.IOSGame=e['iga'];
	$.WebEnabled=e['we'];
	$.WebDrawer=e['wdr'];
	$.WebEditor=e['wed'];
	$.WebGame=e['wga'];
	$.IOSStoreUrl=e['sui'];
	$.AndroidStoreUrl=e['sua'];
	$.WebUrl=e['suw'];
	$.IOSCallback=e['icb'];
	$.AndroidPackageName=e['apn'];
	$.IconBlobLinkString=e['ibls'];
	if(e['ssl']!=null){
		$.ScreenShotsList=[];
		var d = e['ssl'];
		for(var k=0; k<d.length;++k)$.ScreenShotsList.push(new LDAppScreenshot(d[k]));
	}
	if(e['asl']!=null){
		$.AppStoresList=[];
		var d = e['asl'];
		for(var k=0; k<d.length;++k)$.AppStoresList.push(new LDAppStore(d[k]));
	}
	$.Languages=e['lc'];
	$.Name=e['n'];
	$.NameTranslations=e['nt'];
	$.RedirectUris=e['ru'];
	$.VideoPostReportUri=e['vpru'];
	$.VideoPostDomain=e['vpd'];
	$.Description=e['d'];
	$.DescriptionTranslations=e['dt'];
	$.UserCardDomain=e['ucd'];
	$.UserCardFullIOSAppId=e['ucfiai'];
	$.UserCardIOSLinkScheme=e['ucils'];
	$.UserCardTemplate=e['uctpl'];
	$.UserCardWebBackground=e['ucwbg'];
	$.UserCardAssetCardBackground=e['ucacbg'];
	$.UserCardAssetDefaultProfile=e['ucadp'];
	$.UserCardAssetProfileForeground=e['ucapfg'];
	$.UserCardDefaultMessage=e['ucdm'];
	$.UserCardShareTitleTemplate=e['ucstt'];
	$.UserCardShareDescriptionTemplate=e['ucsdt'];
	$.UserCardIOSAppStoreId=e['uciasi'];
	$.AndroidPackageSigningKeySha256s=e['apsks'];
	$.UserCardIntroTitle=e['ucit'];
	$.UserCardIntroDescription=e['ucid'];
	$.PortalBetaMetadata=e['pbmd'];
}
LDAppInfoUserMutable.prototype=new LDItemInfoUserMutable();
LDAppInfoUserMutable.prototype.constructor = LDAppInfoUserMutable;
var _=LDAppInfoUserMutable.prototype;
_.__type="LDAppInfoUserMutable";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDItemInfoUserMutable.prototype.encode.call($,o);
	if($.AndroidEnabled!=null)o['ae']=$.AndroidEnabled;
	if($.AndroidDrawer!=null)o['adr']=$.AndroidDrawer;
	if($.AndroidEditor!=null)o['aed']=$.AndroidEditor;
	if($.AndroidGame!=null)o['aga']=$.AndroidGame;
	if($.IOSEnabled!=null)o['ie']=$.IOSEnabled;
	if($.IOSDrawer!=null)o['idr']=$.IOSDrawer;
	if($.IOSEditor!=null)o['ied']=$.IOSEditor;
	if($.IOSGame!=null)o['iga']=$.IOSGame;
	if($.WebEnabled!=null)o['we']=$.WebEnabled;
	if($.WebDrawer!=null)o['wdr']=$.WebDrawer;
	if($.WebEditor!=null)o['wed']=$.WebEditor;
	if($.WebGame!=null)o['wga']=$.WebGame;
	if($.IOSStoreUrl!=null)o['sui']=$.IOSStoreUrl;
	if($.AndroidStoreUrl!=null)o['sua']=$.AndroidStoreUrl;
	if($.WebUrl!=null)o['suw']=$.WebUrl;
	if($.IOSCallback!=null)o['icb']=$.IOSCallback;
	if($.AndroidPackageName!=null)o['apn']=$.AndroidPackageName;
	if($.IconBlobLinkString!=null)o['ibls']=$.IconBlobLinkString;
	if($.ScreenShotsList!=null) {
		o['ssl']=[];
		var d=$.ScreenShotsList;
		for(var k=0;k<d.length;++k) o['ssl'].push(d[k].encode());
	}
	if($.AppStoresList!=null) {
		o['asl']=[];
		var d=$.AppStoresList;
		for(var k=0;k<d.length;++k) o['asl'].push(d[k].encode());
	}
	if($.Languages!=null)o['lc']=$.Languages;
	if($.Name!=null)o['n']=$.Name;
	if($.NameTranslations!=null)o['nt']=$.NameTranslations;
	if($.RedirectUris!=null)o['ru']=$.RedirectUris;
	if($.VideoPostReportUri!=null)o['vpru']=$.VideoPostReportUri;
	if($.VideoPostDomain!=null)o['vpd']=$.VideoPostDomain;
	if($.Description!=null)o['d']=$.Description;
	if($.DescriptionTranslations!=null)o['dt']=$.DescriptionTranslations;
	if($.UserCardDomain!=null)o['ucd']=$.UserCardDomain;
	if($.UserCardFullIOSAppId!=null)o['ucfiai']=$.UserCardFullIOSAppId;
	if($.UserCardIOSLinkScheme!=null)o['ucils']=$.UserCardIOSLinkScheme;
	if($.UserCardTemplate!=null)o['uctpl']=$.UserCardTemplate;
	if($.UserCardWebBackground!=null)o['ucwbg']=$.UserCardWebBackground;
	if($.UserCardAssetCardBackground!=null)o['ucacbg']=$.UserCardAssetCardBackground;
	if($.UserCardAssetDefaultProfile!=null)o['ucadp']=$.UserCardAssetDefaultProfile;
	if($.UserCardAssetProfileForeground!=null)o['ucapfg']=$.UserCardAssetProfileForeground;
	if($.UserCardDefaultMessage!=null)o['ucdm']=$.UserCardDefaultMessage;
	if($.UserCardShareTitleTemplate!=null)o['ucstt']=$.UserCardShareTitleTemplate;
	if($.UserCardShareDescriptionTemplate!=null)o['ucsdt']=$.UserCardShareDescriptionTemplate;
	if($.UserCardIOSAppStoreId!=null)o['uciasi']=$.UserCardIOSAppStoreId;
	if($.AndroidPackageSigningKeySha256s!=null)o['apsks']=$.AndroidPackageSigningKeySha256s;
	if($.UserCardIntroTitle!=null)o['ucit']=$.UserCardIntroTitle;
	if($.UserCardIntroDescription!=null)o['ucid']=$.UserCardIntroDescription;
	if($.PortalBetaMetadata!=null)o['pbmd']=$.PortalBetaMetadata;
	return o;
}
_.AndroidEnabled=null;
_.AndroidDrawer=null;
_.AndroidEditor=null;
_.AndroidGame=null;
_.IOSEnabled=null;
_.IOSDrawer=null;
_.IOSEditor=null;
_.IOSGame=null;
_.WebEnabled=null;
_.WebDrawer=null;
_.WebEditor=null;
_.WebGame=null;
_.IOSStoreUrl=null;
_.AndroidStoreUrl=null;
_.WebUrl=null;
_.IOSCallback=null;
_.AndroidPackageName=null;
_.IconBlobLinkString=null;
_.ScreenShotsList=null;
_.AppStoresList=null;
_.Languages=null;
_.Name=null;
_.NameTranslations=null;
_.RedirectUris=null;
_.VideoPostReportUri=null;
_.VideoPostDomain=null;
_.Description=null;
_.DescriptionTranslations=null;
_.UserCardDomain=null;
_.UserCardFullIOSAppId=null;
_.UserCardIOSLinkScheme=null;
_.UserCardTemplate=null;
_.UserCardWebBackground=null;
_.UserCardAssetCardBackground=null;
_.UserCardAssetDefaultProfile=null;
_.UserCardAssetProfileForeground=null;
_.UserCardDefaultMessage=null;
_.UserCardShareTitleTemplate=null;
_.UserCardShareDescriptionTemplate=null;
_.UserCardIOSAppStoreId=null;
_.AndroidPackageSigningKeySha256s=null;
_.UserCardIntroTitle=null;
_.UserCardIntroDescription=null;
_.PortalBetaMetadata=null;

module.exports=LDAppInfoUserMutable;
