var LDContentType = {
	"PROFILE_PICTURE": "PROFILE_PICTURE",
	"PROFILE_NAME": "PROFILE_NAME",
	"MESSAGE": "MESSAGE",
	"PUBLIC_CHAT_MESSAGE": "PUBLIC_CHAT_MESSAGE",
	"WALL_POST": "WALL_POST",
	"WALL_POST_COMMENT": "WALL_POST_COMMENT"
};
module.exports=LDContentType;
