var LDRequestContainerBase = require('./LDRequestContainerBase');
var LDDeviceToClusterPresenceRequestProtocol = require('./LDDeviceToClusterPresenceRequestProtocol');
var LDDeviceToClusterUserModerationRequestProtocol = require('./LDDeviceToClusterUserModerationRequestProtocol');
var LDClusterOrDeviceToClusterEventSummaryRequestProtocol = require('./LDClusterOrDeviceToClusterEventSummaryRequestProtocol');
var LDDeviceToClusterProfileCardRequestProtocol = require('./LDDeviceToClusterProfileCardRequestProtocol');
var LDDeviceToClusterPublicChatRequestProtocol = require('./LDDeviceToClusterPublicChatRequestProtocol');
var LDDeviceToClusterIdentityTokenRequestProtocol = require('./LDDeviceToClusterIdentityTokenRequestProtocol');
var LDDeviceToClusterWallPostRequestProtocol = require('./LDDeviceToClusterWallPostRequestProtocol');
var LDDeviceToClusterDirectMessagingRequestProtocol = require('./LDDeviceToClusterDirectMessagingRequestProtocol');
var LDDeviceToClusterMiscellaneousRequestProtocol = require('./LDDeviceToClusterMiscellaneousRequestProtocol');
var LDDeviceToClusterNearbyItemRequestProtocol = require('./LDDeviceToClusterNearbyItemRequestProtocol');
var LDDeviceToClusterHighScoreRequestProtocol = require('./LDDeviceToClusterHighScoreRequestProtocol');
var LDDeviceToClusterSubscriptionRequestProtocol = require('./LDDeviceToClusterSubscriptionRequestProtocol');
var LDDeviceToClusterGameChallengeRequestProtocol = require('./LDDeviceToClusterGameChallengeRequestProtocol');
var LDDeviceToClusterCloudSyncRequestProtocol = require('./LDDeviceToClusterCloudSyncRequestProtocol');
var LDDeviceToClusterDeviceRequestProtocol = require('./LDDeviceToClusterDeviceRequestProtocol');
var LDDeviceToClusterOmletItemStoreRequestProtocol = require('./LDDeviceToClusterOmletItemStoreRequestProtocol');
var LDDeviceToClusterAddressBookRequestProtocol = require('./LDDeviceToClusterAddressBookRequestProtocol');
var LDDeviceToClusterProfileRequestProtocol = require('./LDDeviceToClusterProfileRequestProtocol');
var LDDeviceToClusterContactRequestProtocol = require('./LDDeviceToClusterContactRequestProtocol');
var LDClusterOrDeviceToClusterBlobRequestProtocol = require('./LDClusterOrDeviceToClusterBlobRequestProtocol');
var LDDeviceToClusterInboxRequestProtocol = require('./LDDeviceToClusterInboxRequestProtocol');
var LDDeviceToClusterMessageRequestProtocol = require('./LDDeviceToClusterMessageRequestProtocol');

function LDDeviceToClusterRequestContainer(e){
	LDRequestContainerBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['m']!=null)$.Message=new LDDeviceToClusterMessageRequestProtocol(e['m']);
	if(e['i']!=null)$.Inbox=new LDDeviceToClusterInboxRequestProtocol(e['i']);
	if(e['b']!=null)$.Blob=new LDClusterOrDeviceToClusterBlobRequestProtocol(e['b']);
	if(e['c']!=null)$.Contact=new LDDeviceToClusterContactRequestProtocol(e['c']);
	if(e['p']!=null)$.Profile=new LDDeviceToClusterProfileRequestProtocol(e['p']);
	if(e['a']!=null)$.AddressBook=new LDDeviceToClusterAddressBookRequestProtocol(e['a']);
	if(e['oas']!=null)$.OmletAppStore=new LDDeviceToClusterOmletItemStoreRequestProtocol(e['oas']);
	if(e['d']!=null)$.Device=new LDDeviceToClusterDeviceRequestProtocol(e['d']);
	if(e['cs']!=null)$.CloudSync=new LDDeviceToClusterCloudSyncRequestProtocol(e['cs']);
	if(e['g']!=null)$.GameChallenge=new LDDeviceToClusterGameChallengeRequestProtocol(e['g']);
	if(e['s']!=null)$.Subscription=new LDDeviceToClusterSubscriptionRequestProtocol(e['s']);
	if(e['h']!=null)$.HighScore=new LDDeviceToClusterHighScoreRequestProtocol(e['h']);
	if(e['n']!=null)$.NearbyItem=new LDDeviceToClusterNearbyItemRequestProtocol(e['n']);
	if(e['M']!=null)$.Misc=new LDDeviceToClusterMiscellaneousRequestProtocol(e['M']);
	if(e['o']!=null)$.Oob=new LDDeviceToClusterDirectMessagingRequestProtocol(e['o']);
	if(e['w']!=null)$.WallPost=new LDDeviceToClusterWallPostRequestProtocol(e['w']);
	if(e['t']!=null)$.IdentityToken=new LDDeviceToClusterIdentityTokenRequestProtocol(e['t']);
	if(e['pc']!=null)$.PublicChat=new LDDeviceToClusterPublicChatRequestProtocol(e['pc']);
	if(e['pcv']!=null)$.ProfileCardViewed=new LDDeviceToClusterProfileCardRequestProtocol(e['pcv']);
	if(e['es']!=null)$.EventSummary=new LDClusterOrDeviceToClusterEventSummaryRequestProtocol(e['es']);
	if(e['um']!=null)$.UserModeration=new LDDeviceToClusterUserModerationRequestProtocol(e['um']);
	if(e['ps']!=null)$.Presence=new LDDeviceToClusterPresenceRequestProtocol(e['ps']);
}
LDDeviceToClusterRequestContainer.prototype=new LDRequestContainerBase();
LDDeviceToClusterRequestContainer.prototype.constructor = LDDeviceToClusterRequestContainer;
var _=LDDeviceToClusterRequestContainer.prototype;
_.__type="LDDeviceToClusterRequestContainer";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDRequestContainerBase.prototype.encode.call($,o);
	if($.Message!=null)o['m']=$.Message.encode();
	if($.Inbox!=null)o['i']=$.Inbox.encode();
	if($.Blob!=null)o['b']=$.Blob.encode();
	if($.Contact!=null)o['c']=$.Contact.encode();
	if($.Profile!=null)o['p']=$.Profile.encode();
	if($.AddressBook!=null)o['a']=$.AddressBook.encode();
	if($.OmletAppStore!=null)o['oas']=$.OmletAppStore.encode();
	if($.Device!=null)o['d']=$.Device.encode();
	if($.CloudSync!=null)o['cs']=$.CloudSync.encode();
	if($.GameChallenge!=null)o['g']=$.GameChallenge.encode();
	if($.Subscription!=null)o['s']=$.Subscription.encode();
	if($.HighScore!=null)o['h']=$.HighScore.encode();
	if($.NearbyItem!=null)o['n']=$.NearbyItem.encode();
	if($.Misc!=null)o['M']=$.Misc.encode();
	if($.Oob!=null)o['o']=$.Oob.encode();
	if($.WallPost!=null)o['w']=$.WallPost.encode();
	if($.IdentityToken!=null)o['t']=$.IdentityToken.encode();
	if($.PublicChat!=null)o['pc']=$.PublicChat.encode();
	if($.ProfileCardViewed!=null)o['pcv']=$.ProfileCardViewed.encode();
	if($.EventSummary!=null)o['es']=$.EventSummary.encode();
	if($.UserModeration!=null)o['um']=$.UserModeration.encode();
	if($.Presence!=null)o['ps']=$.Presence.encode();
	return o;
}
_.Message=null;
_.Inbox=null;
_.Blob=null;
_.Contact=null;
_.Profile=null;
_.AddressBook=null;
_.OmletAppStore=null;
_.Device=null;
_.CloudSync=null;
_.GameChallenge=null;
_.Subscription=null;
_.HighScore=null;
_.NearbyItem=null;
_.Misc=null;
_.Oob=null;
_.WallPost=null;
_.IdentityToken=null;
_.PublicChat=null;
_.ProfileCardViewed=null;
_.EventSummary=null;
_.UserModeration=null;
_.Presence=null;

module.exports=LDDeviceToClusterRequestContainer;
