var LDResponseContainerBase = require('./LDResponseContainerBase');
var LDDeviceToClusterAppNotificationResponseProtocol = require('./LDDeviceToClusterAppNotificationResponseProtocol');
var LDDeviceToClusterPresenceResponseProtocol = require('./LDDeviceToClusterPresenceResponseProtocol');
var LDDeviceToClusterUserModerationResponseProtocol = require('./LDDeviceToClusterUserModerationResponseProtocol');
var LDClusterOrDeviceToClusterEventSummaryResponseProtocol = require('./LDClusterOrDeviceToClusterEventSummaryResponseProtocol');
var LDDeviceToClusterProfileCardResponseProtocol = require('./LDDeviceToClusterProfileCardResponseProtocol');
var LDDeviceToClusterPublicChatResponseProtocol = require('./LDDeviceToClusterPublicChatResponseProtocol');
var LDDeviceToClusterIdentityTokenResponseProtocol = require('./LDDeviceToClusterIdentityTokenResponseProtocol');
var LDDeviceToClusterWallPostResponseProtocol = require('./LDDeviceToClusterWallPostResponseProtocol');
var LDDeviceToClusterDirectMessagingResponseProtocol = require('./LDDeviceToClusterDirectMessagingResponseProtocol');
var LDDeviceToClusterMiscellaneousResponseProtocol = require('./LDDeviceToClusterMiscellaneousResponseProtocol');
var LDDeviceToClusterNearbyItemResponseProtocol = require('./LDDeviceToClusterNearbyItemResponseProtocol');
var LDDeviceToClusterHighScoreResponseProtocol = require('./LDDeviceToClusterHighScoreResponseProtocol');
var LDDeviceToClusterSubscriptionResponseProtocol = require('./LDDeviceToClusterSubscriptionResponseProtocol');
var LDDeviceToClusterGameChallengeResponseProtocol = require('./LDDeviceToClusterGameChallengeResponseProtocol');
var LDDeviceToClusterCloudSyncResponseProtocol = require('./LDDeviceToClusterCloudSyncResponseProtocol');
var LDDeviceToClusterDeviceResponseProtocol = require('./LDDeviceToClusterDeviceResponseProtocol');
var LDDeviceToClusterOmletItemStoreResponseProtocol = require('./LDDeviceToClusterOmletItemStoreResponseProtocol');
var LDDeviceToClusterAddressBookResponseProtocol = require('./LDDeviceToClusterAddressBookResponseProtocol');
var LDDeviceToClusterProfileResponseProtocol = require('./LDDeviceToClusterProfileResponseProtocol');
var LDDeviceToClusterContactResponseProtocol = require('./LDDeviceToClusterContactResponseProtocol');
var LDClusterOrDeviceToClusterBlobResponseProtocol = require('./LDClusterOrDeviceToClusterBlobResponseProtocol');
var LDDeviceToClusterInboxResponseProtocol = require('./LDDeviceToClusterInboxResponseProtocol');
var LDDeviceToClusterMessageResponseProtocol = require('./LDDeviceToClusterMessageResponseProtocol');

function O(e){
	LDResponseContainerBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['m']!=null)$.Message=new LDDeviceToClusterMessageResponseProtocol(e['m']);
	if(e['i']!=null)$.Inbox=new LDDeviceToClusterInboxResponseProtocol(e['i']);
	if(e['b']!=null)$.Blob=new LDClusterOrDeviceToClusterBlobResponseProtocol(e['b']);
	if(e['c']!=null)$.Contact=new LDDeviceToClusterContactResponseProtocol(e['c']);
	if(e['p']!=null)$.Profile=new LDDeviceToClusterProfileResponseProtocol(e['p']);
	if(e['a']!=null)$.AddressBook=new LDDeviceToClusterAddressBookResponseProtocol(e['a']);
	if(e['oas']!=null)$.OmletAppStore=new LDDeviceToClusterOmletItemStoreResponseProtocol(e['oas']);
	if(e['d']!=null)$.Device=new LDDeviceToClusterDeviceResponseProtocol(e['d']);
	if(e['cs']!=null)$.CloudSync=new LDDeviceToClusterCloudSyncResponseProtocol(e['cs']);
	if(e['g']!=null)$.GameChallenge=new LDDeviceToClusterGameChallengeResponseProtocol(e['g']);
	if(e['s']!=null)$.Subscription=new LDDeviceToClusterSubscriptionResponseProtocol(e['s']);
	if(e['h']!=null)$.HighScore=new LDDeviceToClusterHighScoreResponseProtocol(e['h']);
	if(e['n']!=null)$.NearbyItem=new LDDeviceToClusterNearbyItemResponseProtocol(e['n']);
	if(e['M']!=null)$.Misc=new LDDeviceToClusterMiscellaneousResponseProtocol(e['M']);
	if(e['o']!=null)$.Oob=new LDDeviceToClusterDirectMessagingResponseProtocol(e['o']);
	if(e['w']!=null)$.WallPost=new LDDeviceToClusterWallPostResponseProtocol(e['w']);
	if(e['t']!=null)$.IdentityToken=new LDDeviceToClusterIdentityTokenResponseProtocol(e['t']);
	if(e['pc']!=null)$.PublicChat=new LDDeviceToClusterPublicChatResponseProtocol(e['pc']);
	if(e['pcv']!=null)$.ProfileCardViewed=new LDDeviceToClusterProfileCardResponseProtocol(e['pcv']);
	if(e['es']!=null)$.EventSummary=new LDClusterOrDeviceToClusterEventSummaryResponseProtocol(e['es']);
	if(e['um']!=null)$.UserModeration=new LDDeviceToClusterUserModerationResponseProtocol(e['um']);
	if(e['ps']!=null)$.Presence=new LDDeviceToClusterPresenceResponseProtocol(e['ps']);
	if(e['nf']!=null)$.Notification=new LDDeviceToClusterAppNotificationResponseProtocol(e['nf']);
}
O.prototype=new LDResponseContainerBase();
O.prototype.constructor = O;
var _=O.prototype;
_.__type="LDDeviceToClusterResponseContainer";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDResponseContainerBase.prototype.encode.call($,o);
	if($.Message!=null)o['m']=$.Message.encode();
	if($.Inbox!=null)o['i']=$.Inbox.encode();
	if($.Blob!=null)o['b']=$.Blob.encode();
	if($.Contact!=null)o['c']=$.Contact.encode();
	if($.Profile!=null)o['p']=$.Profile.encode();
	if($.AddressBook!=null)o['a']=$.AddressBook.encode();
	if($.OmletAppStore!=null)o['oas']=$.OmletAppStore.encode();
	if($.Device!=null)o['d']=$.Device.encode();
	if($.CloudSync!=null)o['cs']=$.CloudSync.encode();
	if($.GameChallenge!=null)o['g']=$.GameChallenge.encode();
	if($.Subscription!=null)o['s']=$.Subscription.encode();
	if($.HighScore!=null)o['h']=$.HighScore.encode();
	if($.NearbyItem!=null)o['n']=$.NearbyItem.encode();
	if($.Misc!=null)o['M']=$.Misc.encode();
	if($.Oob!=null)o['o']=$.Oob.encode();
	if($.WallPost!=null)o['w']=$.WallPost.encode();
	if($.IdentityToken!=null)o['t']=$.IdentityToken.encode();
	if($.PublicChat!=null)o['pc']=$.PublicChat.encode();
	if($.ProfileCardViewed!=null)o['pcv']=$.ProfileCardViewed.encode();
	if($.EventSummary!=null)o['es']=$.EventSummary.encode();
	if($.UserModeration!=null)o['um']=$.UserModeration.encode();
	if($.Presence!=null)o['ps']=$.Presence.encode();
	if($.Notification!=null)o['nf']=$.Notification.encode();
	return o;
}
_.Message=null;
_.Inbox=null;
_.Blob=null;
_.Contact=null;
_.Profile=null;
_.AddressBook=null;
_.OmletAppStore=null;
_.Device=null;
_.CloudSync=null;
_.GameChallenge=null;
_.Subscription=null;
_.HighScore=null;
_.NearbyItem=null;
_.Misc=null;
_.Oob=null;
_.WallPost=null;
_.IdentityToken=null;
_.PublicChat=null;
_.ProfileCardViewed=null;
_.EventSummary=null;
_.UserModeration=null;
_.Presence=null;
_.Notification=null;

module.exports=O;
