var LDRequestProtocolBase = require('./LDRequestProtocolBase');
var LDSendRealtimeMessageToAllFollowersRequest = require('./LDSendRealtimeMessageToAllFollowersRequest');
var LDGetRecommendedWallRequest = require('./LDGetRecommendedWallRequest');
var LDGetPackagesRequest = require('./LDGetPackagesRequest');
var LDUpdatePostDetailsRequest = require('./LDUpdatePostDetailsRequest');
var LDGetPackagePostsRequest = require('./LDGetPackagePostsRequest');
var LDGetUserWallPostCountRequest = require('./LDGetUserWallPostCountRequest');
var LDGetFollowingCountRequest = require('./LDGetFollowingCountRequest');
var LDGetFollowerCountRequest = require('./LDGetFollowerCountRequest');
var LDCheckFollowingRequest = require('./LDCheckFollowingRequest');
var LDGetExternalShareLinkRequest = require('./LDGetExternalShareLinkRequest');
var LDDeletePostRequest = require('./LDDeletePostRequest');
var LDGetAccountsFollowedRequest = require('./LDGetAccountsFollowedRequest');
var LDGetFollowersRequest = require('./LDGetFollowersRequest');
var LDGetStandardPostTagsRequest = require('./LDGetStandardPostTagsRequest');
var LDGetPostRequest = require('./LDGetPostRequest');
var LDGetFollowingWallRequest = require('./LDGetFollowingWallRequest');
var LDGetGameWallRequest = require('./LDGetGameWallRequest');
var LDGetUserWallRequest = require('./LDGetUserWallRequest');
var LDFollowUserRequest = require('./LDFollowUserRequest');
var LDAddViewRequest = require('./LDAddViewRequest');
var LDLikePostRequest = require('./LDLikePostRequest');
var LDPostScreenShotRequest = require('./LDPostScreenShotRequest');
var LDPostMessageRequest = require('./LDPostMessageRequest');
var LDPostVideoRequest = require('./LDPostVideoRequest');

function LDDeviceToClusterWallPostRequestProtocol(e){
	LDRequestProtocolBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['pv']!=null)$.PostVideo=new LDPostVideoRequest(e['pv']);
	if(e['pm']!=null)$.PostMessage=new LDPostMessageRequest(e['pm']);
	if(e['ps']!=null)$.PostScreenShot=new LDPostScreenShotRequest(e['ps']);
	if(e['l']!=null)$.LikePost=new LDLikePostRequest(e['l']);
	if(e['v']!=null)$.AddVideoView=new LDAddViewRequest(e['v']);
	if(e['f']!=null)$.FollowUser=new LDFollowUserRequest(e['f']);
	if(e['guw']!=null)$.GetUserWall=new LDGetUserWallRequest(e['guw']);
	if(e['ggw']!=null)$.GetGameWall=new LDGetGameWallRequest(e['ggw']);
	if(e['gfw']!=null)$.GetFollowingWall=new LDGetFollowingWallRequest(e['gfw']);
	if(e['gp']!=null)$.GetPost=new LDGetPostRequest(e['gp']);
	if(e['gspt']!=null)$.GetStandardPostTags=new LDGetStandardPostTagsRequest(e['gspt']);
	if(e['gf']!=null)$.GetFollowers=new LDGetFollowersRequest(e['gf']);
	if(e['gaf']!=null)$.GetAccountsFollowedRequest=new LDGetAccountsFollowedRequest(e['gaf']);
	if(e['dp']!=null)$.DeletePostRequest=new LDDeletePostRequest(e['dp']);
	if(e['ges']!=null)$.GetExternalShareLink=new LDGetExternalShareLinkRequest(e['ges']);
	if(e['cf']!=null)$.CheckFollowing=new LDCheckFollowingRequest(e['cf']);
	if(e['gfc']!=null)$.GetFollowerCount=new LDGetFollowerCountRequest(e['gfc']);
	if(e['gafc']!=null)$.GetFollowingCount=new LDGetFollowingCountRequest(e['gafc']);
	if(e['guwc']!=null)$.GetUserWallPostCount=new LDGetUserWallPostCountRequest(e['guwc']);
	if(e['gpp']!=null)$.GetPackagePosts=new LDGetPackagePostsRequest(e['gpp']);
	if(e['upd']!=null)$.UpdatePostDetailsRequest=new LDUpdatePostDetailsRequest(e['upd']);
	if(e['gppi']!=null)$.GetPackagesRequest=new LDGetPackagesRequest(e['gppi']);
	if(e['grw']!=null)$.GetRecommendedWallRequest=new LDGetRecommendedWallRequest(e['grw']);
	if(e['sr']!=null)$.SendRealtimeMessageToAllFollowersRequest=new LDSendRealtimeMessageToAllFollowersRequest(e['sr']);
}
LDDeviceToClusterWallPostRequestProtocol.prototype=new LDRequestProtocolBase();
LDDeviceToClusterWallPostRequestProtocol.prototype.constructor = LDDeviceToClusterWallPostRequestProtocol;
var _=LDDeviceToClusterWallPostRequestProtocol.prototype;
_.__type="LDDeviceToClusterWallPostRequestProtocol";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDRequestProtocolBase.prototype.encode.call($,o);
	if($.PostVideo!=null)o['pv']=$.PostVideo.encode();
	if($.PostMessage!=null)o['pm']=$.PostMessage.encode();
	if($.PostScreenShot!=null)o['ps']=$.PostScreenShot.encode();
	if($.LikePost!=null)o['l']=$.LikePost.encode();
	if($.AddVideoView!=null)o['v']=$.AddVideoView.encode();
	if($.FollowUser!=null)o['f']=$.FollowUser.encode();
	if($.GetUserWall!=null)o['guw']=$.GetUserWall.encode();
	if($.GetGameWall!=null)o['ggw']=$.GetGameWall.encode();
	if($.GetFollowingWall!=null)o['gfw']=$.GetFollowingWall.encode();
	if($.GetPost!=null)o['gp']=$.GetPost.encode();
	if($.GetStandardPostTags!=null)o['gspt']=$.GetStandardPostTags.encode();
	if($.GetFollowers!=null)o['gf']=$.GetFollowers.encode();
	if($.GetAccountsFollowedRequest!=null)o['gaf']=$.GetAccountsFollowedRequest.encode();
	if($.DeletePostRequest!=null)o['dp']=$.DeletePostRequest.encode();
	if($.GetExternalShareLink!=null)o['ges']=$.GetExternalShareLink.encode();
	if($.CheckFollowing!=null)o['cf']=$.CheckFollowing.encode();
	if($.GetFollowerCount!=null)o['gfc']=$.GetFollowerCount.encode();
	if($.GetFollowingCount!=null)o['gafc']=$.GetFollowingCount.encode();
	if($.GetUserWallPostCount!=null)o['guwc']=$.GetUserWallPostCount.encode();
	if($.GetPackagePosts!=null)o['gpp']=$.GetPackagePosts.encode();
	if($.UpdatePostDetailsRequest!=null)o['upd']=$.UpdatePostDetailsRequest.encode();
	if($.GetPackagesRequest!=null)o['gppi']=$.GetPackagesRequest.encode();
	if($.GetRecommendedWallRequest!=null)o['grw']=$.GetRecommendedWallRequest.encode();
	if($.SendRealtimeMessageToAllFollowersRequest!=null)o['sr']=$.SendRealtimeMessageToAllFollowersRequest.encode();
	return o;
}
_.PostVideo=null;
_.PostMessage=null;
_.PostScreenShot=null;
_.LikePost=null;
_.AddVideoView=null;
_.FollowUser=null;
_.GetUserWall=null;
_.GetGameWall=null;
_.GetFollowingWall=null;
_.GetPost=null;
_.GetStandardPostTags=null;
_.GetFollowers=null;
_.GetAccountsFollowedRequest=null;
_.DeletePostRequest=null;
_.GetExternalShareLink=null;
_.CheckFollowing=null;
_.GetFollowerCount=null;
_.GetFollowingCount=null;
_.GetUserWallPostCount=null;
_.GetPackagePosts=null;
_.UpdatePostDetailsRequest=null;
_.GetPackagesRequest=null;
_.GetRecommendedWallRequest=null;
_.SendRealtimeMessageToAllFollowersRequest=null;

module.exports=LDDeviceToClusterWallPostRequestProtocol;
