var LDRequestProtocolBase = require('./LDRequestProtocolBase');
var LDPromotePostRequest = require('./LDPromotePostRequest');
var LDGetFeaturedVideosRequest = require('./LDGetFeaturedVideosRequest');
var LDSetFeaturedVideoRequest = require('./LDSetFeaturedVideoRequest');
var LDGetClippedVideosForPackageRequest = require('./LDGetClippedVideosForPackageRequest');
var LDGetNonfeaturedPackagesRequest = require('./LDGetNonfeaturedPackagesRequest');
var LDGetSuggestedCommunitiesRequest = require('./LDGetSuggestedCommunitiesRequest');
var LDGetHistoryRequest = require('./LDGetHistoryRequest');
var LDGetTrendingCommunitiesRequest = require('./LDGetTrendingCommunitiesRequest');
var LDGetCommunityInfosRequest = require('./LDGetCommunityInfosRequest');
var LDGetAppDetailsRequest = require('./LDGetAppDetailsRequest');
var LDDeleteCommentRequest = require('./LDDeleteCommentRequest');
var LDGetUserCommentsRequest = require('./LDGetUserCommentsRequest');
var LDGetCommentsRequest = require('./LDGetCommentsRequest');
var LDAddCommentRequest = require('./LDAddCommentRequest');
var LDResolveCanonicalCommunityIdsRequest = require('./LDResolveCanonicalCommunityIdsRequest');
var LDGetCommunitiesRequest = require('./LDGetCommunitiesRequest');
var LDLeaveCommunityRequest = require('./LDLeaveCommunityRequest');
var LDJoinCommunityRequest = require('./LDJoinCommunityRequest');
var LDUploadCommunityDetailsRequest = require('./LDUploadCommunityDetailsRequest');
var LDGetTrendingPostsRequest = require('./LDGetTrendingPostsRequest');
var LDGetRecentPostsRequest = require('./LDGetRecentPostsRequest');
var LDListAppsByPopularityRequest = require('./LDListAppsByPopularityRequest');
var LDSendRealtimeMessageToAllFollowersRequest = require('./LDSendRealtimeMessageToAllFollowersRequest');
var LDGetRecommendedWallRequest = require('./LDGetRecommendedWallRequest');
var LDGetAllCommunitiesRequest = require('./LDGetAllCommunitiesRequest');
var LDUpdatePostDetailsRequest = require('./LDUpdatePostDetailsRequest');
var LDGetPackagePostsRequest = require('./LDGetPackagePostsRequest');
var LDGetUserWallPostCountRequest = require('./LDGetUserWallPostCountRequest');
var LDGetFollowingCountRequest = require('./LDGetFollowingCountRequest');
var LDGetFollowerCountRequest = require('./LDGetFollowerCountRequest');
var LDCheckFollowingMeRequest = require('./LDCheckFollowingMeRequest');
var LDCheckFollowingRequest = require('./LDCheckFollowingRequest');
var LDGetExternalShareLinkRequest = require('./LDGetExternalShareLinkRequest');
var LDDeletePostRequest = require('./LDDeletePostRequest');
var LDGetAccountsFollowedRequest = require('./LDGetAccountsFollowedRequest');
var LDGetFollowersRequest = require('./LDGetFollowersRequest');
var LDGetStandardPostTagsRequest = require('./LDGetStandardPostTagsRequest');
var LDGetPostRequest = require('./LDGetPostRequest');
var LDGetFollowingWallRequest = require('./LDGetFollowingWallRequest');
var LDGetGameWallRequest = require('./LDGetGameWallRequest');
var LDGetUserWallRequest = require('./LDGetUserWallRequest');
var LDFollowUserRequest = require('./LDFollowUserRequest');
var LDAddViewRequest = require('./LDAddViewRequest');
var LDLikePostRequest = require('./LDLikePostRequest');
var LDPostMiniclipRequest = require('./LDPostMiniclipRequest');
var LDPostScreenShotRequest = require('./LDPostScreenShotRequest');
var LDPostMessageRequest = require('./LDPostMessageRequest');
var LDPostVideoRequest = require('./LDPostVideoRequest');

function O(e){
	LDRequestProtocolBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['pv']!=null)$.PostVideo=new LDPostVideoRequest(e['pv']);
	if(e['pm']!=null)$.PostMessage=new LDPostMessageRequest(e['pm']);
	if(e['ps']!=null)$.PostScreenShot=new LDPostScreenShotRequest(e['ps']);
	if(e['pmc']!=null)$.PostMiniclip=new LDPostMiniclipRequest(e['pmc']);
	if(e['l']!=null)$.LikePost=new LDLikePostRequest(e['l']);
	if(e['v']!=null)$.AddVideoView=new LDAddViewRequest(e['v']);
	if(e['f']!=null)$.FollowUser=new LDFollowUserRequest(e['f']);
	if(e['guw']!=null)$.GetUserWall=new LDGetUserWallRequest(e['guw']);
	if(e['ggw']!=null)$.GetGameWall=new LDGetGameWallRequest(e['ggw']);
	if(e['gfw']!=null)$.GetFollowingWall=new LDGetFollowingWallRequest(e['gfw']);
	if(e['gp']!=null)$.GetPost=new LDGetPostRequest(e['gp']);
	if(e['gspt']!=null)$.GetStandardPostTags=new LDGetStandardPostTagsRequest(e['gspt']);
	if(e['gf']!=null)$.GetFollowers=new LDGetFollowersRequest(e['gf']);
	if(e['gaf']!=null)$.GetAccountsFollowedRequest=new LDGetAccountsFollowedRequest(e['gaf']);
	if(e['dp']!=null)$.DeletePostRequest=new LDDeletePostRequest(e['dp']);
	if(e['ges']!=null)$.GetExternalShareLink=new LDGetExternalShareLinkRequest(e['ges']);
	if(e['cf']!=null)$.CheckFollowing=new LDCheckFollowingRequest(e['cf']);
	if(e['cfm']!=null)$.CheckFollowingMe=new LDCheckFollowingMeRequest(e['cfm']);
	if(e['gfc']!=null)$.GetFollowerCount=new LDGetFollowerCountRequest(e['gfc']);
	if(e['gafc']!=null)$.GetFollowingCount=new LDGetFollowingCountRequest(e['gafc']);
	if(e['guwc']!=null)$.GetUserWallPostCount=new LDGetUserWallPostCountRequest(e['guwc']);
	if(e['gpp']!=null)$.GetPackagePosts=new LDGetPackagePostsRequest(e['gpp']);
	if(e['upd']!=null)$.UpdatePostDetailsRequest=new LDUpdatePostDetailsRequest(e['upd']);
	if(e['gppi']!=null)$.GetAllCommunitiesRequest=new LDGetAllCommunitiesRequest(e['gppi']);
	if(e['grw']!=null)$.GetRecommendedWallRequest=new LDGetRecommendedWallRequest(e['grw']);
	if(e['sr']!=null)$.SendRealtimeMessageToAllFollowersRequest=new LDSendRealtimeMessageToAllFollowersRequest(e['sr']);
	if(e['la']!=null)$.ListAppsByPopularityRequest=new LDListAppsByPopularityRequest(e['la']);
	if(e['grp']!=null)$.GetRecentPostsRequest=new LDGetRecentPostsRequest(e['grp']);
	if(e['gtp']!=null)$.GetTrendingPostsRequest=new LDGetTrendingPostsRequest(e['gtp']);
	if(e['ucd']!=null)$.UploadCommunityDetailsRequest=new LDUploadCommunityDetailsRequest(e['ucd']);
	if(e['ag']!=null)$.AddGameRequest=new LDJoinCommunityRequest(e['ag']);
	if(e['rg']!=null)$.RemoveGameRequest=new LDLeaveCommunityRequest(e['rg']);
	if(e['gg']!=null)$.GetGamesRequest=new LDGetCommunitiesRequest(e['gg']);
	if(e['rcpid']!=null)$.ResolveCanonicalPackageIdsRequest=new LDResolveCanonicalCommunityIdsRequest(e['rcpid']);
	if(e['ac']!=null)$.AddCommentRequest=new LDAddCommentRequest(e['ac']);
	if(e['gc']!=null)$.GetCommentsRequest=new LDGetCommentsRequest(e['gc']);
	if(e['guc']!=null)$.GetUserCommentsRequest=new LDGetUserCommentsRequest(e['guc']);
	if(e['dc']!=null)$.DeleteCommentRequest=new LDDeleteCommentRequest(e['dc']);
	if(e['gad']!=null)$.GetAppDetailsRequest=new LDGetAppDetailsRequest(e['gad']);
	if(e['gci']!=null)$.GetCommunityInfoRequest=new LDGetCommunityInfosRequest(e['gci']);
	if(e['gtc']!=null)$.GetTrendingCommunitiesRequest=new LDGetTrendingCommunitiesRequest(e['gtc']);
	if(e['gh']!=null)$.GetHistoryRequest=new LDGetHistoryRequest(e['gh']);
	if(e['gsc']!=null)$.GetSuggestedCommunitiesRequest=new LDGetSuggestedCommunitiesRequest(e['gsc']);
	if(e['lfv']!=null)$.GetNonfeaturedPackagesRequest=new LDGetNonfeaturedPackagesRequest(e['lfv']);
	if(e['gcv']!=null)$.GetClippedVideosForPackageRequest=new LDGetClippedVideosForPackageRequest(e['gcv']);
	if(e['sfv']!=null)$.SetFeaturedVideoRequest=new LDSetFeaturedVideoRequest(e['sfv']);
	if(e['gfv']!=null)$.GetFeaturedVideosRequest=new LDGetFeaturedVideosRequest(e['gfv']);
	if(e['pp']!=null)$.PromotePostRequest=new LDPromotePostRequest(e['pp']);
}
O.prototype=new LDRequestProtocolBase();
O.prototype.constructor = O;
var _=O.prototype;
_.__type="LDDeviceToClusterWallPostRequestProtocol";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDRequestProtocolBase.prototype.encode.call($,o);
	if($.PostVideo!=null)o['pv']=$.PostVideo.encode();
	if($.PostMessage!=null)o['pm']=$.PostMessage.encode();
	if($.PostScreenShot!=null)o['ps']=$.PostScreenShot.encode();
	if($.PostMiniclip!=null)o['pmc']=$.PostMiniclip.encode();
	if($.LikePost!=null)o['l']=$.LikePost.encode();
	if($.AddVideoView!=null)o['v']=$.AddVideoView.encode();
	if($.FollowUser!=null)o['f']=$.FollowUser.encode();
	if($.GetUserWall!=null)o['guw']=$.GetUserWall.encode();
	if($.GetGameWall!=null)o['ggw']=$.GetGameWall.encode();
	if($.GetFollowingWall!=null)o['gfw']=$.GetFollowingWall.encode();
	if($.GetPost!=null)o['gp']=$.GetPost.encode();
	if($.GetStandardPostTags!=null)o['gspt']=$.GetStandardPostTags.encode();
	if($.GetFollowers!=null)o['gf']=$.GetFollowers.encode();
	if($.GetAccountsFollowedRequest!=null)o['gaf']=$.GetAccountsFollowedRequest.encode();
	if($.DeletePostRequest!=null)o['dp']=$.DeletePostRequest.encode();
	if($.GetExternalShareLink!=null)o['ges']=$.GetExternalShareLink.encode();
	if($.CheckFollowing!=null)o['cf']=$.CheckFollowing.encode();
	if($.CheckFollowingMe!=null)o['cfm']=$.CheckFollowingMe.encode();
	if($.GetFollowerCount!=null)o['gfc']=$.GetFollowerCount.encode();
	if($.GetFollowingCount!=null)o['gafc']=$.GetFollowingCount.encode();
	if($.GetUserWallPostCount!=null)o['guwc']=$.GetUserWallPostCount.encode();
	if($.GetPackagePosts!=null)o['gpp']=$.GetPackagePosts.encode();
	if($.UpdatePostDetailsRequest!=null)o['upd']=$.UpdatePostDetailsRequest.encode();
	if($.GetAllCommunitiesRequest!=null)o['gppi']=$.GetAllCommunitiesRequest.encode();
	if($.GetRecommendedWallRequest!=null)o['grw']=$.GetRecommendedWallRequest.encode();
	if($.SendRealtimeMessageToAllFollowersRequest!=null)o['sr']=$.SendRealtimeMessageToAllFollowersRequest.encode();
	if($.ListAppsByPopularityRequest!=null)o['la']=$.ListAppsByPopularityRequest.encode();
	if($.GetRecentPostsRequest!=null)o['grp']=$.GetRecentPostsRequest.encode();
	if($.GetTrendingPostsRequest!=null)o['gtp']=$.GetTrendingPostsRequest.encode();
	if($.UploadCommunityDetailsRequest!=null)o['ucd']=$.UploadCommunityDetailsRequest.encode();
	if($.AddGameRequest!=null)o['ag']=$.AddGameRequest.encode();
	if($.RemoveGameRequest!=null)o['rg']=$.RemoveGameRequest.encode();
	if($.GetGamesRequest!=null)o['gg']=$.GetGamesRequest.encode();
	if($.ResolveCanonicalPackageIdsRequest!=null)o['rcpid']=$.ResolveCanonicalPackageIdsRequest.encode();
	if($.AddCommentRequest!=null)o['ac']=$.AddCommentRequest.encode();
	if($.GetCommentsRequest!=null)o['gc']=$.GetCommentsRequest.encode();
	if($.GetUserCommentsRequest!=null)o['guc']=$.GetUserCommentsRequest.encode();
	if($.DeleteCommentRequest!=null)o['dc']=$.DeleteCommentRequest.encode();
	if($.GetAppDetailsRequest!=null)o['gad']=$.GetAppDetailsRequest.encode();
	if($.GetCommunityInfoRequest!=null)o['gci']=$.GetCommunityInfoRequest.encode();
	if($.GetTrendingCommunitiesRequest!=null)o['gtc']=$.GetTrendingCommunitiesRequest.encode();
	if($.GetHistoryRequest!=null)o['gh']=$.GetHistoryRequest.encode();
	if($.GetSuggestedCommunitiesRequest!=null)o['gsc']=$.GetSuggestedCommunitiesRequest.encode();
	if($.GetNonfeaturedPackagesRequest!=null)o['lfv']=$.GetNonfeaturedPackagesRequest.encode();
	if($.GetClippedVideosForPackageRequest!=null)o['gcv']=$.GetClippedVideosForPackageRequest.encode();
	if($.SetFeaturedVideoRequest!=null)o['sfv']=$.SetFeaturedVideoRequest.encode();
	if($.GetFeaturedVideosRequest!=null)o['gfv']=$.GetFeaturedVideosRequest.encode();
	if($.PromotePostRequest!=null)o['pp']=$.PromotePostRequest.encode();
	return o;
}
_.PostVideo=null;
_.PostMessage=null;
_.PostScreenShot=null;
_.PostMiniclip=null;
_.LikePost=null;
_.AddVideoView=null;
_.FollowUser=null;
_.GetUserWall=null;
_.GetGameWall=null;
_.GetFollowingWall=null;
_.GetPost=null;
_.GetStandardPostTags=null;
_.GetFollowers=null;
_.GetAccountsFollowedRequest=null;
_.DeletePostRequest=null;
_.GetExternalShareLink=null;
_.CheckFollowing=null;
_.CheckFollowingMe=null;
_.GetFollowerCount=null;
_.GetFollowingCount=null;
_.GetUserWallPostCount=null;
_.GetPackagePosts=null;
_.UpdatePostDetailsRequest=null;
_.GetAllCommunitiesRequest=null;
_.GetRecommendedWallRequest=null;
_.SendRealtimeMessageToAllFollowersRequest=null;
_.ListAppsByPopularityRequest=null;
_.GetRecentPostsRequest=null;
_.GetTrendingPostsRequest=null;
_.UploadCommunityDetailsRequest=null;
_.AddGameRequest=null;
_.RemoveGameRequest=null;
_.GetGamesRequest=null;
_.ResolveCanonicalPackageIdsRequest=null;
_.AddCommentRequest=null;
_.GetCommentsRequest=null;
_.GetUserCommentsRequest=null;
_.DeleteCommentRequest=null;
_.GetAppDetailsRequest=null;
_.GetCommunityInfoRequest=null;
_.GetTrendingCommunitiesRequest=null;
_.GetHistoryRequest=null;
_.GetSuggestedCommunitiesRequest=null;
_.GetNonfeaturedPackagesRequest=null;
_.GetClippedVideosForPackageRequest=null;
_.SetFeaturedVideoRequest=null;
_.GetFeaturedVideosRequest=null;
_.PromotePostRequest=null;

module.exports=O;
