var LDRequestProtocolBase = require('./LDRequestProtocolBase');
var LDGetPermissionsRequest = require('./LDGetPermissionsRequest');
var LDAdminBlockUserRequest = require('./LDAdminBlockUserRequest');
var LDAdminUnbanUserFromAppRequest = require('./LDAdminUnbanUserFromAppRequest');
var LDAdminBanUserFromAppRequest = require('./LDAdminBanUserFromAppRequest');
var LDAdminUnbanUserRequest = require('./LDAdminUnbanUserRequest');
var LDAdminBanUserRequest = require('./LDAdminBanUserRequest');
var LDCreateCountryWideFeedRequest = require('./LDCreateCountryWideFeedRequest');
var LDDeleteScheduledJobRequest = require('./LDDeleteScheduledJobRequest');
var LDGetDeviceRecordsRequest = require('./LDGetDeviceRecordsRequest');
var LDLogUserOutRequest = require('./LDLogUserOutRequest');
var LDDisableUserGameChallengeRequest = require('./LDDisableUserGameChallengeRequest');
var LDChangeUserProfilePictureRequest = require('./LDChangeUserProfilePictureRequest');
var LDChangeUserNameRequest = require('./LDChangeUserNameRequest');
var LDListFlaggedUsersRequest = require('./LDListFlaggedUsersRequest');
var LDGetIdentityRecordsRequest = require('./LDGetIdentityRecordsRequest');
var LDGetAccountDetailsByIdentityRequest = require('./LDGetAccountDetailsByIdentityRequest');
var LDGetAccountDetailsByAccountRequest = require('./LDGetAccountDetailsByAccountRequest');
var LDGetEmailLoginLinkRequest = require('./LDGetEmailLoginLinkRequest');
var LDUnblockIdentityRequest = require('./LDUnblockIdentityRequest');

function LDDeviceToIdpAdministrativeRequestProtocol(e){
	LDRequestProtocolBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['u']!=null)$.UnblockIdentity=new LDUnblockIdentityRequest(e['u']);
	if(e['e']!=null)$.GetEmailLoginLink=new LDGetEmailLoginLinkRequest(e['e']);
	if(e['a']!=null)$.GetDetailsByAccount=new LDGetAccountDetailsByAccountRequest(e['a']);
	if(e['i']!=null)$.GetDetailsByIdentity=new LDGetAccountDetailsByIdentityRequest(e['i']);
	if(e['I']!=null)$.GetIdentityRecordsRequest=new LDGetIdentityRecordsRequest(e['I']);
	if(e['f']!=null)$.ListFlaggedUsers=new LDListFlaggedUsersRequest(e['f']);
	if(e['n']!=null)$.ChangeUserName=new LDChangeUserNameRequest(e['n']);
	if(e['p']!=null)$.ChangeUserPicture=new LDChangeUserProfilePictureRequest(e['p']);
	if(e['g']!=null)$.DisableGameChallenge=new LDDisableUserGameChallengeRequest(e['g']);
	if(e['l']!=null)$.LogUserOut=new LDLogUserOutRequest(e['l']);
	if(e['d']!=null)$.GetDeviceRecords=new LDGetDeviceRecordsRequest(e['d']);
	if(e['ds']!=null)$.DeleteScheduledJobRequest=new LDDeleteScheduledJobRequest(e['ds']);
	if(e['cf']!=null)$.CreateCountryWideFeedRequest=new LDCreateCountryWideFeedRequest(e['cf']);
	if(e['bu']!=null)$.BanUserRequest=new LDAdminBanUserRequest(e['bu']);
	if(e['uu']!=null)$.UnbanUserRequest=new LDAdminUnbanUserRequest(e['uu']);
	if(e['bua']!=null)$.BanUserFromAppRequest=new LDAdminBanUserFromAppRequest(e['bua']);
	if(e['uua']!=null)$.UnbanUserFromAppRequest=new LDAdminUnbanUserFromAppRequest(e['uua']);
	if(e['blu']!=null)$.BlockUserRequest=new LDAdminBlockUserRequest(e['blu']);
	if(e['gp']!=null)$.GetPermissionsRequest=new LDGetPermissionsRequest(e['gp']);
}
LDDeviceToIdpAdministrativeRequestProtocol.prototype=new LDRequestProtocolBase();
LDDeviceToIdpAdministrativeRequestProtocol.prototype.constructor = LDDeviceToIdpAdministrativeRequestProtocol;
var _=LDDeviceToIdpAdministrativeRequestProtocol.prototype;
_.__type="LDDeviceToIdpAdministrativeRequestProtocol";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDRequestProtocolBase.prototype.encode.call($,o);
	if($.UnblockIdentity!=null)o['u']=$.UnblockIdentity.encode();
	if($.GetEmailLoginLink!=null)o['e']=$.GetEmailLoginLink.encode();
	if($.GetDetailsByAccount!=null)o['a']=$.GetDetailsByAccount.encode();
	if($.GetDetailsByIdentity!=null)o['i']=$.GetDetailsByIdentity.encode();
	if($.GetIdentityRecordsRequest!=null)o['I']=$.GetIdentityRecordsRequest.encode();
	if($.ListFlaggedUsers!=null)o['f']=$.ListFlaggedUsers.encode();
	if($.ChangeUserName!=null)o['n']=$.ChangeUserName.encode();
	if($.ChangeUserPicture!=null)o['p']=$.ChangeUserPicture.encode();
	if($.DisableGameChallenge!=null)o['g']=$.DisableGameChallenge.encode();
	if($.LogUserOut!=null)o['l']=$.LogUserOut.encode();
	if($.GetDeviceRecords!=null)o['d']=$.GetDeviceRecords.encode();
	if($.DeleteScheduledJobRequest!=null)o['ds']=$.DeleteScheduledJobRequest.encode();
	if($.CreateCountryWideFeedRequest!=null)o['cf']=$.CreateCountryWideFeedRequest.encode();
	if($.BanUserRequest!=null)o['bu']=$.BanUserRequest.encode();
	if($.UnbanUserRequest!=null)o['uu']=$.UnbanUserRequest.encode();
	if($.BanUserFromAppRequest!=null)o['bua']=$.BanUserFromAppRequest.encode();
	if($.UnbanUserFromAppRequest!=null)o['uua']=$.UnbanUserFromAppRequest.encode();
	if($.BlockUserRequest!=null)o['blu']=$.BlockUserRequest.encode();
	if($.GetPermissionsRequest!=null)o['gp']=$.GetPermissionsRequest.encode();
	return o;
}
_.UnblockIdentity=null;
_.GetEmailLoginLink=null;
_.GetDetailsByAccount=null;
_.GetDetailsByIdentity=null;
_.GetIdentityRecordsRequest=null;
_.ListFlaggedUsers=null;
_.ChangeUserName=null;
_.ChangeUserPicture=null;
_.DisableGameChallenge=null;
_.LogUserOut=null;
_.GetDeviceRecords=null;
_.DeleteScheduledJobRequest=null;
_.CreateCountryWideFeedRequest=null;
_.BanUserRequest=null;
_.UnbanUserRequest=null;
_.BanUserFromAppRequest=null;
_.UnbanUserFromAppRequest=null;
_.BlockUserRequest=null;
_.GetPermissionsRequest=null;

module.exports=LDDeviceToIdpAdministrativeRequestProtocol;
