var LDResponseProtocolBase = require('./LDResponseProtocolBase');
var LDGetFeaturedVideosResponse = require('./LDGetFeaturedVideosResponse');
var LDGetClippedVideosForPackageResponse = require('./LDGetClippedVideosForPackageResponse');
var LDGetNonfeaturedPackagesResponse = require('./LDGetNonfeaturedPackagesResponse');
var LDGetSuggestedCommunitiesResponse = require('./LDGetSuggestedCommunitiesResponse');
var LDGetHistoryResponse = require('./LDGetHistoryResponse');
var LDGetTrendingCommunitiesResponse = require('./LDGetTrendingCommunitiesResponse');
var LDGetCommunityInfosResponse = require('./LDGetCommunityInfosResponse');
var LDGetAppDetailsResponse = require('./LDGetAppDetailsResponse');
var LDGetCommentsResponse = require('./LDGetCommentsResponse');
var LDResolveCanonicalCommunityIdsResponse = require('./LDResolveCanonicalCommunityIdsResponse');
var LDGetCommunitiesResponse = require('./LDGetCommunitiesResponse');
var LDListAppsByPopularityResponse = require('./LDListAppsByPopularityResponse');
var LDGetAllCommunitiesResponse = require('./LDGetAllCommunitiesResponse');
var LDGetExternalShareLinkResponse = require('./LDGetExternalShareLinkResponse');
var LDGetFollowersResponse = require('./LDGetFollowersResponse');
var LDGetStandardPostTagsResponse = require('./LDGetStandardPostTagsResponse');
var LDGetAccountsFollowedResponse = require('./LDGetAccountsFollowedResponse');
var LDAddPostResponse = require('./LDAddPostResponse');
var LDGetPostResponse = require('./LDGetPostResponse');
var LDWallsResponse = require('./LDWallsResponse');
var LDWallResponse = require('./LDWallResponse');

function O(e){
	LDResponseProtocolBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['w']!=null)$.WallResponse=new LDWallResponse(e['w']);
	if(e['ws']!=null)$.WallsResponse=new LDWallsResponse(e['ws']);
	if(e['gp']!=null)$.GetPostResponse=new LDGetPostResponse(e['gp']);
	if(e['ap']!=null)$.AddPostResponse=new LDAddPostResponse(e['ap']);
	if(e['gaf']!=null)$.GetAccountsFollowedResponse=new LDGetAccountsFollowedResponse(e['gaf']);
	if(e['gspt']!=null)$.GetStandardPostTagsResponse=new LDGetStandardPostTagsResponse(e['gspt']);
	if(e['gf']!=null)$.GetFollowersResponse=new LDGetFollowersResponse(e['gf']);
	if(e['ges']!=null)$.GetExternalShareLink=new LDGetExternalShareLinkResponse(e['ges']);
	if(e['gppi']!=null)$.GetAllCommunitiesResponse=new LDGetAllCommunitiesResponse(e['gppi']);
	if(e['la']!=null)$.ListAppsByPopularityResponse=new LDListAppsByPopularityResponse(e['la']);
	if(e['gcm']!=null)$.GetCommunitiesResponse=new LDGetCommunitiesResponse(e['gcm']);
	if(e['rccid']!=null)$.ResolveCanonicalPackageIdsResponse=new LDResolveCanonicalCommunityIdsResponse(e['rccid']);
	if(e['gc']!=null)$.GetCommentsResponse=new LDGetCommentsResponse(e['gc']);
	if(e['gad']!=null)$.GetAppDetailsResponse=new LDGetAppDetailsResponse(e['gad']);
	if(e['gci']!=null)$.GetCommunityInfoResponse=new LDGetCommunityInfosResponse(e['gci']);
	if(e['gtc']!=null)$.GetTrendingCommunitiesResponse=new LDGetTrendingCommunitiesResponse(e['gtc']);
	if(e['gh']!=null)$.GetHistoryResponse=new LDGetHistoryResponse(e['gh']);
	if(e['gsc']!=null)$.GetSuggestedCommunitiesResponse=new LDGetSuggestedCommunitiesResponse(e['gsc']);
	if(e['lfv']!=null)$.GetNonfeaturedPackagesResponse=new LDGetNonfeaturedPackagesResponse(e['lfv']);
	if(e['gcv']!=null)$.GetClippedVideosForPackageResponse=new LDGetClippedVideosForPackageResponse(e['gcv']);
	if(e['gfv']!=null)$.GetFeaturedVideosResponse=new LDGetFeaturedVideosResponse(e['gfv']);
}
O.prototype=new LDResponseProtocolBase();
O.prototype.constructor = O;
var _=O.prototype;
_.__type="LDDeviceToClusterWallPostResponseProtocol";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDResponseProtocolBase.prototype.encode.call($,o);
	if($.WallResponse!=null)o['w']=$.WallResponse.encode();
	if($.WallsResponse!=null)o['ws']=$.WallsResponse.encode();
	if($.GetPostResponse!=null)o['gp']=$.GetPostResponse.encode();
	if($.AddPostResponse!=null)o['ap']=$.AddPostResponse.encode();
	if($.GetAccountsFollowedResponse!=null)o['gaf']=$.GetAccountsFollowedResponse.encode();
	if($.GetStandardPostTagsResponse!=null)o['gspt']=$.GetStandardPostTagsResponse.encode();
	if($.GetFollowersResponse!=null)o['gf']=$.GetFollowersResponse.encode();
	if($.GetExternalShareLink!=null)o['ges']=$.GetExternalShareLink.encode();
	if($.GetAllCommunitiesResponse!=null)o['gppi']=$.GetAllCommunitiesResponse.encode();
	if($.ListAppsByPopularityResponse!=null)o['la']=$.ListAppsByPopularityResponse.encode();
	if($.GetCommunitiesResponse!=null)o['gcm']=$.GetCommunitiesResponse.encode();
	if($.ResolveCanonicalPackageIdsResponse!=null)o['rccid']=$.ResolveCanonicalPackageIdsResponse.encode();
	if($.GetCommentsResponse!=null)o['gc']=$.GetCommentsResponse.encode();
	if($.GetAppDetailsResponse!=null)o['gad']=$.GetAppDetailsResponse.encode();
	if($.GetCommunityInfoResponse!=null)o['gci']=$.GetCommunityInfoResponse.encode();
	if($.GetTrendingCommunitiesResponse!=null)o['gtc']=$.GetTrendingCommunitiesResponse.encode();
	if($.GetHistoryResponse!=null)o['gh']=$.GetHistoryResponse.encode();
	if($.GetSuggestedCommunitiesResponse!=null)o['gsc']=$.GetSuggestedCommunitiesResponse.encode();
	if($.GetNonfeaturedPackagesResponse!=null)o['lfv']=$.GetNonfeaturedPackagesResponse.encode();
	if($.GetClippedVideosForPackageResponse!=null)o['gcv']=$.GetClippedVideosForPackageResponse.encode();
	if($.GetFeaturedVideosResponse!=null)o['gfv']=$.GetFeaturedVideosResponse.encode();
	return o;
}
_.WallResponse=null;
_.WallsResponse=null;
_.GetPostResponse=null;
_.AddPostResponse=null;
_.GetAccountsFollowedResponse=null;
_.GetStandardPostTagsResponse=null;
_.GetFollowersResponse=null;
_.GetExternalShareLink=null;
_.GetAllCommunitiesResponse=null;
_.ListAppsByPopularityResponse=null;
_.GetCommunitiesResponse=null;
_.ResolveCanonicalPackageIdsResponse=null;
_.GetCommentsResponse=null;
_.GetAppDetailsResponse=null;
_.GetCommunityInfoResponse=null;
_.GetTrendingCommunitiesResponse=null;
_.GetHistoryResponse=null;
_.GetSuggestedCommunitiesResponse=null;
_.GetNonfeaturedPackagesResponse=null;
_.GetClippedVideosForPackageResponse=null;
_.GetFeaturedVideosResponse=null;

module.exports=O;
