var LDRequestProtocolBase = require('./LDRequestProtocolBase');
var LDMessageTerminatedPush = require('./LDMessageTerminatedPush');
var LDRealtimeMessageDeliveryPush = require('./LDRealtimeMessageDeliveryPush');
var LDMessageDeliveryPush = require('./LDMessageDeliveryPush');
var LDApplyDocumentTransformRequest = require('./LDApplyDocumentTransformRequest');
var LDGetPublicFeedDetailsRequest = require('./LDGetPublicFeedDetailsRequest');
var LDSetDefaultAccessRequest = require('./LDSetDefaultAccessRequest');
var LDJoinBroadcastRequest = require('./LDJoinBroadcastRequest');
var LDJoinFeedRequest = require('./LDJoinFeedRequest');
var LDGetJoinFeedLinkRequest = require('./LDGetJoinFeedLinkRequest');
var LDRemovePendingInvitationRequest = require('./LDRemovePendingInvitationRequest');
var LDAddPendingInvitationRequest = require('./LDAddPendingInvitationRequest');
var LDSendRealtimeToAccountsRequest = require('./LDSendRealtimeToAccountsRequest');
var LDSendRealtimeRequest = require('./LDSendRealtimeRequest');
var LDSetFeedVideoRequest = require('./LDSetFeedVideoRequest');
var LDSetFeedThumbnailRequest = require('./LDSetFeedThumbnailRequest');
var LDSetFeedNameRequest = require('./LDSetFeedNameRequest');
var LDRemoveMemberRequest = require('./LDRemoveMemberRequest');
var LDAddMemberRequest = require('./LDAddMemberRequest');
var LDUnsubscribeFeedRealtimeRequest = require('./LDUnsubscribeFeedRealtimeRequest');
var LDSubscribeFeedRealtimeRequest = require('./LDSubscribeFeedRealtimeRequest');
var LDUnsubscribeFeedRequest = require('./LDUnsubscribeFeedRequest');
var LDSubscribeFeedRequest = require('./LDSubscribeFeedRequest');
var LDDeleteMessageRequest = require('./LDDeleteMessageRequest');
var LDOverwriteMessageRequest = require('./LDOverwriteMessageRequest');
var LDUpdateMessageRequest = require('./LDUpdateMessageRequest');
var LDAddMessageRequest = require('./LDAddMessageRequest');
var LDGetMessageByIdRequest = require('./LDGetMessageByIdRequest');
var LDGetMessagesByTypeRequest = require('./LDGetMessagesByTypeRequest');
var LDGetMessagesBeforeRequest = require('./LDGetMessagesBeforeRequest');
var LDGetMessagesSinceRequest = require('./LDGetMessagesSinceRequest');
var LDCreateFeedRequest = require('./LDCreateFeedRequest');

function LDDeviceToClusterMessageRequestProtocol(e){
	LDRequestProtocolBase.call(this,e);
	if(!e)return;
	var $=this;
	if(e['c']!=null)$.CreateFeed=new LDCreateFeedRequest(e['c']);
	if(e['s']!=null)$.GetMessagesSince=new LDGetMessagesSinceRequest(e['s']);
	if(e['b']!=null)$.GetMessagesBefore=new LDGetMessagesBeforeRequest(e['b']);
	if(e['T']!=null)$.GetMessagesByType=new LDGetMessagesByTypeRequest(e['T']);
	if(e['i']!=null)$.GetMessageById=new LDGetMessageByIdRequest(e['i']);
	if(e['a']!=null)$.AddMessage=new LDAddMessageRequest(e['a']);
	if(e['u']!=null)$.UpdateMessage=new LDUpdateMessageRequest(e['u']);
	if(e['o']!=null)$.OverwriteMessage=new LDOverwriteMessageRequest(e['o']);
	if(e['d']!=null)$.DeleteMessage=new LDDeleteMessageRequest(e['d']);
	if(e['S']!=null)$.SubscribeFeed=new LDSubscribeFeedRequest(e['S']);
	if(e['U']!=null)$.UnsubscribeFeed=new LDUnsubscribeFeedRequest(e['U']);
	if(e['l']!=null)$.SubscribeFeedRealtime=new LDSubscribeFeedRealtimeRequest(e['l']);
	if(e['q']!=null)$.UnsubscribeFeedRealtime=new LDUnsubscribeFeedRealtimeRequest(e['q']);
	if(e['g']!=null)$.AddMember=new LDAddMemberRequest(e['g']);
	if(e['r']!=null)$.RemoveMember=new LDRemoveMemberRequest(e['r']);
	if(e['n']!=null)$.SetFeedName=new LDSetFeedNameRequest(e['n']);
	if(e['h']!=null)$.SetFeedThumbnail=new LDSetFeedThumbnailRequest(e['h']);
	if(e['hv']!=null)$.SetFeedVideo=new LDSetFeedVideoRequest(e['hv']);
	if(e['L']!=null)$.SendRealtime=new LDSendRealtimeRequest(e['L']);
	if(e['LA']!=null)$.SendRealtimeToAccounts=new LDSendRealtimeToAccountsRequest(e['LA']);
	if(e['f']!=null)$.AddPendingInvitation=new LDAddPendingInvitationRequest(e['f']);
	if(e['e']!=null)$.RemovePendingInvitation=new LDRemovePendingInvitationRequest(e['e']);
	if(e['j']!=null)$.GetJoinFeedLink=new LDGetJoinFeedLinkRequest(e['j']);
	if(e['J']!=null)$.JoinFeed=new LDJoinFeedRequest(e['J']);
	if(e['B']!=null)$.JoinBroadcast=new LDJoinBroadcastRequest(e['B']);
	if(e['x']!=null)$.DefaultAccess=new LDSetDefaultAccessRequest(e['x']);
	if(e['gf']!=null)$.GetFeedDetails=new LDGetPublicFeedDetailsRequest(e['gf']);
	if(e['D']!=null)$.ApplyDocumentRequest=new LDApplyDocumentTransformRequest(e['D']);
	if(e['p']!=null)$.MessageDeliveryPush=new LDMessageDeliveryPush(e['p']);
	if(e['P']!=null)$.RealtimeMessageDeliveryPush=new LDRealtimeMessageDeliveryPush(e['P']);
	if(e['t']!=null)$.TerminatedPush=new LDMessageTerminatedPush(e['t']);
}
LDDeviceToClusterMessageRequestProtocol.prototype=new LDRequestProtocolBase();
LDDeviceToClusterMessageRequestProtocol.prototype.constructor = LDDeviceToClusterMessageRequestProtocol;
var _=LDDeviceToClusterMessageRequestProtocol.prototype;
_.__type="LDDeviceToClusterMessageRequestProtocol";
_.encode=function(o){
	if(o===undefined)o={};
	var $=this;
	LDRequestProtocolBase.prototype.encode.call($,o);
	if($.CreateFeed!=null)o['c']=$.CreateFeed.encode();
	if($.GetMessagesSince!=null)o['s']=$.GetMessagesSince.encode();
	if($.GetMessagesBefore!=null)o['b']=$.GetMessagesBefore.encode();
	if($.GetMessagesByType!=null)o['T']=$.GetMessagesByType.encode();
	if($.GetMessageById!=null)o['i']=$.GetMessageById.encode();
	if($.AddMessage!=null)o['a']=$.AddMessage.encode();
	if($.UpdateMessage!=null)o['u']=$.UpdateMessage.encode();
	if($.OverwriteMessage!=null)o['o']=$.OverwriteMessage.encode();
	if($.DeleteMessage!=null)o['d']=$.DeleteMessage.encode();
	if($.SubscribeFeed!=null)o['S']=$.SubscribeFeed.encode();
	if($.UnsubscribeFeed!=null)o['U']=$.UnsubscribeFeed.encode();
	if($.SubscribeFeedRealtime!=null)o['l']=$.SubscribeFeedRealtime.encode();
	if($.UnsubscribeFeedRealtime!=null)o['q']=$.UnsubscribeFeedRealtime.encode();
	if($.AddMember!=null)o['g']=$.AddMember.encode();
	if($.RemoveMember!=null)o['r']=$.RemoveMember.encode();
	if($.SetFeedName!=null)o['n']=$.SetFeedName.encode();
	if($.SetFeedThumbnail!=null)o['h']=$.SetFeedThumbnail.encode();
	if($.SetFeedVideo!=null)o['hv']=$.SetFeedVideo.encode();
	if($.SendRealtime!=null)o['L']=$.SendRealtime.encode();
	if($.SendRealtimeToAccounts!=null)o['LA']=$.SendRealtimeToAccounts.encode();
	if($.AddPendingInvitation!=null)o['f']=$.AddPendingInvitation.encode();
	if($.RemovePendingInvitation!=null)o['e']=$.RemovePendingInvitation.encode();
	if($.GetJoinFeedLink!=null)o['j']=$.GetJoinFeedLink.encode();
	if($.JoinFeed!=null)o['J']=$.JoinFeed.encode();
	if($.JoinBroadcast!=null)o['B']=$.JoinBroadcast.encode();
	if($.DefaultAccess!=null)o['x']=$.DefaultAccess.encode();
	if($.GetFeedDetails!=null)o['gf']=$.GetFeedDetails.encode();
	if($.ApplyDocumentRequest!=null)o['D']=$.ApplyDocumentRequest.encode();
	if($.MessageDeliveryPush!=null)o['p']=$.MessageDeliveryPush.encode();
	if($.RealtimeMessageDeliveryPush!=null)o['P']=$.RealtimeMessageDeliveryPush.encode();
	if($.TerminatedPush!=null)o['t']=$.TerminatedPush.encode();
	return o;
}
_.CreateFeed=null;
_.GetMessagesSince=null;
_.GetMessagesBefore=null;
_.GetMessagesByType=null;
_.GetMessageById=null;
_.AddMessage=null;
_.UpdateMessage=null;
_.OverwriteMessage=null;
_.DeleteMessage=null;
_.SubscribeFeed=null;
_.UnsubscribeFeed=null;
_.SubscribeFeedRealtime=null;
_.UnsubscribeFeedRealtime=null;
_.AddMember=null;
_.RemoveMember=null;
_.SetFeedName=null;
_.SetFeedThumbnail=null;
_.SetFeedVideo=null;
_.SendRealtime=null;
_.SendRealtimeToAccounts=null;
_.AddPendingInvitation=null;
_.RemovePendingInvitation=null;
_.GetJoinFeedLink=null;
_.JoinFeed=null;
_.JoinBroadcast=null;
_.DefaultAccess=null;
_.GetFeedDetails=null;
_.ApplyDocumentRequest=null;
_.MessageDeliveryPush=null;
_.RealtimeMessageDeliveryPush=null;
_.TerminatedPush=null;

module.exports=LDDeviceToClusterMessageRequestProtocol;
